sonar.projectKey=Rafieaydin_TA_c95365d0-b599-4338-a48b-148b3b3ff1e8
sonar.projectName=HRMS Custom Project
sonar.sources=.


sonar.sources=hrms_custom/hrms_custom
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**, **/__pycache__/**, **/node_modules/**, **/public/js/dist/**
sonar.sourceEncoding=UTF-8